connections {
  gw-transport {
    version = 2
    local_addrs = 10.0.0.3
    remote_addrs = 10.0.0.2
    proposals = aes128-sha256-modp2048
    local  { auth = psk
             id = gw-b }
    remote { auth = psk
             id = gw-a }
    children {
      net-t {
        local_ts  = 10.0.0.3/32
        remote_ts = 10.0.0.2/32
        mode = transport
        esp_proposals = aes128-sha256-modp2048
      }
    }
  }
}
secrets {
  ike-1 {
    id-1 = gw-a
    id-2 = gw-b
    secret = "labpsk-change-me"
  }
}
